version: '2'
services:
  db:
    image: postgres
    container_name: {{name}}_db
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    ports:
      - 5432:5432
    volumes:
      - ../dkdata/postgres:/var/lib/postgresql/data
  nginx:
    image: nginx
    container_name: {{name}}_nginx
    network_mode: "host"
    volumes:
      - ../nginx/default_local:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
